[workspace]
resolver = "3"
members = ["agent","server"]

[workspace.dependencies]
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["macros", "net", "rt", "io-util"] }
